stages:
  - test
  - qa
  - staging

variables:
  CONTAINER_SERVER: "nginx-amblema"
  
  # Path to QA
  PATH_FOLDER_QA: /home/amblema/amblema---backoffice/qa
  PATH_PROJECT_QA: $PATH_FOLDER_QA/amblema---backoffice

  # Path to staging
  PATH_FOLDER_STAGING: /home/amblema/amblema---backoffice/staging
  PATH_PROJECT_STAGING: $PATH_FOLDER_QA/amblema---backoffice

# Jobs for QA environment

update-qa-environment:
  stage: qa
  script:
    - cd $PATH_PROJECT_QA 
    - git config user.email "franklin@binauraldev.com"
    - git config user.name "franklinp"
    - git stash
    - git pull $CI_REPOSITORY_URL qaestable
  tags:
    - amblema
  only:
    - qaestable

run-tests-qa: 
  stage: qa
  image: devbinaural/angular:8.0.0
  script:
    - npm install && ng test --browsers ChromeHeadlessNoSandbox --watch=false
  tags:
    - amblema-angular
  only:
    - qaestable
  when: manual

deploy-qa-environment:
  stage: qa
  image: devbinaural/angular:8.0.0
  script:
    - cd $PATH_PROJECT_QA 
    - docker-compose up build_amblema_backoffice
    - docker restart $CONTAINER_SERVER
  tags:
    - amblema
  only:
    - qaestable  

turn-off-qa:
  stage: qa
  script:
    - cd $PATH_PROJECT_QA
    - rm -rf dist/
  tags:
    - amblema
  only:
    - qaestable
  when: manual

# Jobs for Staging environment

update-staging-environment:
  stage: staging
  script:
    - cd $PATH_PROJECT_STAGING
    - git config user.email "franklin@binauraldev.com"
    - git config user.name "franklinp"
    - git pull $CI_REPOSITORY_URL staging
  tags:
    - amblema
  only:
    - staging

deploy-staging-environment:
  stage: staging
  script:
    - cd $PATH_PROJECT_STAGING 
    - docker-compose up build_amblema_backoffice
    - docker restart $CONTAINER_SERVER
  tags:
    - amblema
  only:
    - staging

turn-off-staging:
  stage: staging
  script:
    - cd $PATH_PROJECT_STAGING
    - rm -rf dist/
  tags:
    - amblema
  only:
    - staging
  when: manual