stages:
  - build-image
  - test
  - build
  - cleanup
  - deploy
  - deploy-support

variables:
  CONTAINER_RUN: "running_amblema_backoffice"
  CONTAINER_SUPPORT: "amblema-backoffice-support"
  CONTAINER_SERVER: "nginx-amblema"

build-image:
  stage: building
  tags: amblema
  script:
    - docker build -f deploy.Dockerfile -t angular:amblema-backoffice .
    - docker run --name $CONTAINER_RUN -v ${PWD}:/app -v /app/node_modules angular:amblema-backoffice
  only:
    - master
    - support

build:
  stage: building-app
  tags: amblema
  script:
    - docker exec $CONTAINER_RUN bash -c "npm install && npm run build:prod"
  only:
    - master
    - support

cleanup:
  stage: cleaning
  tags: amblema
  script:
    - docker container rm $CONTAINER_RUN --force
    - docker rmi angular:amblema-backoffice --force
    - docker-compose down
  only:
    - master
    - support

deploy-support:
  stage: deploying_support
  tags: amblema
  script:
    - if [ "$(docker ps -q -f name=$CONTAINER_SUPPORT)" ]; then
    -   echo "container exist"
    -   docker restart $CONTAINER_SUPPORT
    - else
    -   echo "container does not exist"
    -   docker run -it -d --name $CONTAINER_SUPPORT -p 10503:10503 -v ${PWD}/dist/browser/:/usr/share/nginx/html/Amblema-BackOffice -v ${PWD}/server/:/etc/nginx/ devbinaural/nginx
    -   echo "container created!"
    - fi
  only:
    - support
