stages:
  - build-image
  - test
  - build
  - cleanup
  - deploy
  - deploy-support

variables:
  CONTAINER_RUN: "running_amblema_backoffice"
  CONTAINER_SUPPORT: "amblema-backoffice-support"
  CONTAINER_SERVER: "nginx-amblema"

building:
  stage: build-image
  tags: 
    - amblema
  script:
    - docker build -f deploy.Dockerfile -t angular:amblema-backoffice .
    - docker run --name $CONTAINER_RUN -t -d -v ${PWD}:/app -v /app/node_modules angular:amblema-backoffice
  only:
    - master
    - support


building-app:
  stage: build
  tags: 
    - amblema
  script:
    - docker exec $CONTAINER_RUN bash -c "npm install && npm run build:prod"
    - docker exec $CONTAINER_RUN bash -c "usermod -u 1018 node && chown -R node:node node_modules/ && chown -R node:node dist/"
  only:
    - master
    - support

cleaning:
  stage: cleanup
  tags: 
    - amblema
  script:
    - docker container rm $CONTAINER_RUN --force
    - docker rmi angular:amblema-backoffice --force
  only:
    - master
    - support

deploying_support:
  stage: deploy-support
  tags: 
    - amblema
  script:
    - if [ "$(docker ps -q -f name=$CONTAINER_SUPPORT)" ]; then
    -   echo "container exist"
    -   docker restart $CONTAINER_SUPPORT
    - else
    -   echo "container does not exist"
    -   docker run -it -d --name $CONTAINER_SUPPORT -p 10503:10503 -v ${PWD}/dist/browser/:/usr/share/nginx/html/Amblema-BackOffice -v ${PWD}/server/:/etc/nginx/ devbinaural/nginx
    -   echo "container created!"
    - fi
  only:
    - support
