# # docker-compose up run_amblema_backoffice -> Up Local
# version: "3.7"

# services:
#   # # LOCAL DEV
#   # dev_amblema_backoffice:
#   #   #image: angular:dev # Dockerfile
#   #   build: .
#   #   container_name: amblema-backoffice-dev-qa
#   #   command: bash -c "npm install && ng serve --host 0.0.0.0"
#   #   volumes:
#   #     - "${PWD}:/app"
#   #   ports:
#   #     - $OUT_PORT:4200

#   staging_amblema_backoffice:
#     image: devbinaural/angular:8.0.0
#     container_name: amblema-backoffice-staging
#     command: bash -c "npm run build:prod && usermod -u 1018 node && chown -R node:node node_modules/ && chown -R node:node dist/ && chown node:node ./dist"
#     # command: ls -la -a

#     volumes:
#       - "${PWD}:/app"
#       - "/app/node_modules"
#   # NGINX
#   nginx_amblema:
#     image: devbinaural/nginx # Docker hub Binaural
#     container_name: nginx-amblema
#     volumes:
#       - "./dist/browser/:/usr/share/nginx/html/Amblema-BackOffice/"
#       - "./server/:/etc/nginx/"
#     ports:
#       - $OUT_PORT:10502

#USO-LOCAL - Use command docker-compose -f docker-compose.staging.yml up to set this specific .yml and up the docker-compose
version: "3.5"
services:
  web:
    container_name: amblema_backoffice_staging
    image: devbinaural/nginx-angular:latest
    tty: true
    working_dir: "/home/amblema"
    ports:
      - $OUT_PORT:80
    env_file:
      - .env
    volumes:
      - ./:/home/amblema
      - ./vhost-template.conf:/etc/nginx/conf.d/default.conf
    command: >
      /bin/bash -c "exec nginx -g 'daemon off;'"
